#!/bin/bash
## note: save file as du-fixes-h2.sh
ULB='/usr/local/bin/'
DUF=$ULB'du-fixes-h2.sh'
if [ "$(id -u)" -ne 0 ]
then
	echo "Error: You must be root to run this script!"
	exit 1
else
	if [ -x $DUF ]
	then
		exec $DUF
	else
		cd $ULB
		[ ! -f $DUF ] && wget -Nc http://techpatterns.com/du-fixes
		if [ -f $DUF ]
		then
			chmod +x $DUF
			exec $DUF
			exit 0
		else
			echo "Failed to download script!"
			exit 1
		fi
	fi
fi