#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
	exit 1
fi

DPI=100

[ "$1" ] && DPI="$1"

[ -e /etc/kde4/kdm/Xservers ] && perl -pi -e "s|(/usr/X11R6/bin/X -nolisten tcp).*|\1 -dpi $DPI -br|" /etc/kde3/kdm/Xservers
[ -e /etc/kde4/kdm/kdmrc ] &&    perl -pi -e "s|(ServerArgsLocal=-nolisten tcp).*|\1 -dpi $DPI -br|"  /etc/kde3/kdm/kdmrc
[ -e /var/run/kdm/kdmrc ] &&    perl -pi -e "s|(ServerArgsLocal=-nolisten tcp).*|\1 -dpi $DPI -br|"   /var/run/kdm/kdmrc

echo "KDM setting was changed to $DPI. You can use another value like:"
echo "$0 75"
echo "Now restart X (Ctrl-Alt-Backspace)"

