#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"

	echo Error: You must be root to run this script!
	exit 1
fi

hwclock -s --localtime

NTPSERVERS="pool.ntp.org"

sed s/^NTPSERVERS\=.*/NTPSERVERS\=\"pool.ntp.org\"/ /etc/default/ntpdate

update-rc.d -f ntpdate remove
update-rc.d ntpdate defaults

/etc/init.d/ntpdate start

ntpdate -u -b $NTPSERVERS && hwclock --systohc

