#!/bin/sh
if test $(id -u) != 0; then
	echo Error: You must be root to run this script!
	exit 1
fi

hwclock -s --localtime

NTPSERVERS="pool.ntp.org"

echo NTPSERVERS=$NTPSERVERS > /etc/default/ntp-servers

update-rc.d -f ntpdate remove
update-rc.d ntpdate defaults

/etc/init.d/ntpdate start

ntpdate -u -b $NTPSERVERS && hwclock --systohc

