#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
	printf "ERROR: $(basename ${0}) needs root capabilities, please start it as root.\n\n" >&2
	exit 1
fi

DPI=100
[ "${1}" ] && DPI="${1}"

if [ ${DPI} -eq ${DPI} ]; then
	[ -e /etc/kde3/kdm/kdmrc ] && sed -i "s|\(^ServerArgsLocal=\).*|\1 -br -nolisten tcp -dpi ${DPI}|" /etc/kde3/kdm/kdmrc
	[ -e /etc/kde4/kdm/kdmrc ] && sed -i "s|\(^ServerArgsLocal=\).*|\1 -br -nolisten tcp -dpi ${DPI}|" /etc/kde4/kdm/kdmrc
	[ -e /var/run/kdm/kdmrc ]  && sed -i "s|\(^ServerArgsLocal=\).*|\1 -br -nolisten tcp -dpi ${DPI}|" /var/run/kdm/kdmrc

	printf "KDM setting was changed to $DPI. You can use another value like:\n"
	printf "$(basename ${0}) 75\n"
	printf "Now restart X (Ctrl-Alt-Backspace)\n\n"
else
	echo "ERROR: parameter ${DPI} not a number." >&2
	echo "Usage: $(basename ${0}) [dpi]" >&2
fi
