#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"

	echo Error: You must be root to run this script!
	exit 1
fi

cat <<EOF >/etc/motd
Welcome to $HOSTNAME (Kernel $(uname -r))

EOF
cat /etc/motd

