#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"

	echo Error: You must be root to run this script!
	exit 1
fi

# get time servers from /etc/default/ntpdate
. /etc/default/ntpdate
[ -z "$NTPSERVER" ] && NTPSERVER="pool.ntp.org"

# assume the hw clock being in local time
hwclock --hctosys --localtime

# let the user set their time zone
tzselect

# sync with time servers
for i in $NTPSERVER; do
	if ntpdate -u -b "$i"; then
		hwclock --systohc
		break
	fi
done

