.TH fix-dpi-kdm "3" "January 2015" "fix-dpi-kdm [OPTIONS]" "User Commands (1)"
.SH NAME
fix-dpi-kdm - reconfigure KDE for the given dpi value
.SH SYNOPSIS
.B fix-dpi-kdm
[\fIOPTIONS\fR]
.SH DESCRIPTION
`fix-dpi-kdm' modifies kdm's configuration (/etc/kde4/kdm/kdmrc) to apply the
given dpi value, overriding automatically detected values.
.TP
dpi
Numeric representation of the chosen dpi value.
.SH "SEE ALSO"
.BR kdm
.SH AUTHOR
This manual has been written by Stefan Lippers-Hollmann <s.l-h@gmx.de> for 
the Debian project (but may be used by others).
