#!/bin/sh

[ "$UID" -ne 0 ] && exec kanotix-su "$0" "$@"

# override tool behaviour through distro-defaults
FLL_IMAGE_DIR="KNOPPIX"
FLL_DISTRO_MODE="installed"
[ -r /etc/default/distro ] && source /etc/default/distro

if [ "$FLL_DISTRO_MODE" = "live" ]; then
	if grep -q unionfs /proc/mounts; then
		echo Unionfs found.
	else
		echo Activating Unionfs now.
		mkdir -p /tmp/union
		mount -t unionfs -o dirs="/tmp/union/:/$FLL_IMAGE_DIR" /none "/$FLL_IMAGE_DIR/" 2>&1 >/dev/null
	fi
fi

