#!/usr/bin/perl
#
# Copyright 2009 Niall Walsh <niallwalsh@users.berlios.de>
# License: GPLv2
#
# Script to convert fw-data.ini file to html
#
# Takes filename of ini file as input or defaults to fw-data.ini
# Writes (bare) html to stdout
#

# TODO add some options
my $indent="\t\t\t\t";
my $level="\t";

use strict;
my $file=$1;
if (length($file)==0)
{
	$file='fw-data.ini';
}
unless (-f $file)
{
	die "you must supply a valid filename to load from if fw-data.ini is not in the working directory";
}


# Using Config::Any instead would allow to switch to anything it supports
#use Config::Any;
#my $cfg = Config::Any->load_files({files => [ $file ] });
#my $cards = $$cfg[0]{$file};
use Config::Tiny;
my $cards = Config::Tiny->read($file);

# name and num are used to loop over the cards and build up:
#   @names is the list of sorted ini section names
#   %names is a hash of the ini section names to their sorted number
#   %class holds an array of sections in a class by number
my $name;
my $num=0;
my (@names, %names, %class);

# these are the fields we loop over in this order for content of output
my (@fieldnames)=(
	'drivers',
	'ok',
	'fw',
	'url',
	'note'
);

# go through the ini sections and build up [@%]names and $class
foreach $name (sort(keys(%$cards)))
{
	my $field;
	foreach $field (@fieldnames,'class','title')
	{
		$$cards{$name}{$field}=~s/^\s*\"\s*(.+?)\s*\"\s*$/$1/;
	}
	push(@names,$name);
	$names{$name}=$num;
	$$cards{$name}{'class'}='other' unless (length($$cards{$name}{'class'}));
	my @class = split(/\s+/,$$cards{$name}{'class'});
	my $class;
	my $classCSS;
	foreach $class (@class)
	{
		$classCSS=$class;
		$classCSS=~s/\./\-/g;
		push(@{$$cards{$name}{'_class'}},$classCSS);
		if (!(defined($class{$class})))
		{
			$class{$class}=[$num];
		}
		else
		{
			push(@{$class{$class}},$num);
		}
		
	}
	$num++;
}

sub closetags () {
	my $count=shift();
	unless ($count)
	{
		unshift(@{$_[0]},$count);
		$count=@{$_[0]};
	}
	$count = @{$_[0]} - $count;
	while (@{$_[0]} > $count)
	{
		print $indent;
		my $loop;
		for ($loop=1;$loop<@{$_[0]};$loop++) {
			print $level;
		}
		print pop(@{$_[0]})."\n";
	}
}

sub writefile () {
	my $file=shift();
	if ( -r $file )
	{
		open(IN,$file)||die "failed to open $file : $!";
		my $line;
		while ($line=<IN>)
		{
			print "$line";
		}
		close(IN);
	}
}

&writefile('fw-html.header');

# go through the classes to put them in their own section
my $class;
my $classCSS;
print $indent . '<ul class="firmware">'."\n";
foreach $class (sort(keys(%class)))
{
	$classCSS=$class;
	$classCSS=~s/\./-/g;
	print $indent . $level . '<li><a href="#' . $classCSS . '">' . $class . '</a></li>' . "\n";
}
print $indent . '</ul>' . "\n";

my @close;
print $indent . '<dl class="firmware">' . "\n";
push(@close,'</dl>');
foreach $class (sort(keys(%class)))
{
	$classCSS=$class;
	$classCSS=~s/\./-/g;
	print $indent . $level . '<dt class="' . $classCSS . '"><a name="' . $class . '">' . $class . '</a></dt>' . "\n" .
		$indent . $level . '<dd class="devices">' . "\n" .
		$indent . $level . $level . '<dl class="class">' . "\n";
	# does layer them out on close, and could elsewhere if required
	push(@close,'</dd>','</dl>');
	my $prefix=$level.$level.$level;

	# will have the name and number of the ini section
	my $dname;
	my $dnum;
	# the ini sections in the class
	foreach $dnum (@{$class{$class}})
	{
		my $dname = $names[$dnum];
		print $indent . $prefix . '<dt class="device ' . $$cards{$dname}{'class'} . '" id="' . $dname .'">' . $$cards{$dname}{'title'} . '</dt>' . "\n" . $indent . $prefix . '<dd>' . "\n$indent" . $prefix . $level . '<dl class="dvals">' . "\n";
		push(@close,'</dd>','</dl>');
		my $field;
		# the main fields in the ini section
		foreach $field (@fieldnames)
		{
			if (defined($$cards{$dname}{$field})) {
				my @content=();
				my $content;
				foreach $content (split(/\s+/,$$cards{$dname}{$field}))
				{
					if (($content=~/\ /)||($content!~/^[fh]t+ps?\:\/\//))
					{
						push(@content,$content);
					}
					else
					{
						push(@content,'<a href="' . $content . '">' . $content . '</a>');
					}
				}
				print $indent . $prefix . $level . $level  . '<dt class="' . $field . '"></dt>' . "\n" .
					$indent . $prefix . $level . $level . '<dd>' . join(' ',@content) . '</dd>' . "\n";
			}
		}
		&closetags(2, \@close);
	}
	&closetags((@close-1), \@close);
}
&closetags((@close*1),\@close);

&writefile('fw-html.footer');
