#!/bin/sh
###############################################################
#
# Author: Andreas Weber <andreas@it-weber.com>
# Date: 16.01.2007
# Purpose: Script to install the sidux-binary-gfx Package
#
# Changelog:
# * 16.01.2007 Andreas Weber: Initial Release
#
#
# Todo:
#
#
###############################################################

sources_backup() {
	# We backup sources.list
	cp /etc/apt/sources.list /etc/apt/sources.backup
	cat > "/etc/apt/sources.list" \
	<<EOF
deb http://ftp.debian.org/debian/ sid main contrib non-free
deb http://sidux.com/debian/ sid main fix.main contrib non-free
EOF
	apt-get update || nuke_me
}

sources_restore() {
	# Restoring original sources.list
	cp /etc/apt/sources.backup /etc/apt/sources.list
}

clean_up() {
	# Running apt-get update to avoid apt errors
	apt-get update || nuke_me
}

install_me() {
	# Install the Package
	apt-get install sidux-binary-gfx
	sources_restore
	echo "You can run \"install-binary-gfx -a\" now to build/install the Driver"
	exit 0
}

nuke_me() {
	# If something goes wrong we restore the original sources.list before we left
	[ -f /etc/apt/sources.backup ] && cp /etc/apt/sources.backup /etc/apt/sources.list
	rm -f /etc/apt/sources.backup
	exit 1
}

# We have to be root. Oherwise we exit with exitcode 1
if [ "$(id -u)" -ne 0 ]; then
	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"
	echo Error: You must be root to run this script!
	exit 1
fi

echo "Script to install sidux-binary-gfx"
echo ""

DATE=$(date +%D\ %T)
ME=$(basename $0)

trap nuke_me exit

sources_backup
dpkg -l | grep sidux-binary-gfx || install_me

#END
