#!/bin/sh
###############################################################
#
# Author: Andreas Weber <andreas@it-weber.com>
# Date: 16.01.2007
# Purpose: Script to install the sidux-binary-gfx Package
#
# Changelog:
# * 16.01.2007 Andreas Weber: Initial Release
#
#
# Todo:
#
#
###############################################################

sources_backup() {
	# We backup sources.list
	echo " * Creating Backup of sources.list"
	cp /etc/apt/sources.list /etc/apt/sources.backup
	cat > "/etc/apt/sources.list" \
	<<EOF
deb http://ftp.debian.org/debian/ sid main contrib non-free
deb http://sidux.com/debian/ sid main fix.main contrib non-free
EOF
	echo " * Running apt-get update"	
	apt-get update > /dev/null || nuke_me
}

sources_restore() {
	# Restoring original sources.list
	echo " * Restoring original sources.list"
	cp /etc/apt/sources.backup /etc/apt/sources.list
}

clean_up() {
	# Running apt-get update to avoid apt errors
	echo " * Running apt-get update to fix the cache"
	apt-get update > /dev/null || nuke_me
}

install_me() {
	# Install the Package
	echo " * Install sidux-binary-gfx"
	apt-get install sidux-binary-gfx > /dev/null
	sources_restore
}

nuke_me() {
	# If something goes wrong we restore the original sources.list before we left
	[ -f /etc/apt/sources.backup ] && cp /etc/apt/sources.backup /etc/apt/sources.list
	rm -f /etc/apt/sources.backup
	exit 0
}

# We have to be root. Oherwise we exit with exitcode 1
if [ "$(id -u)" -ne 0 ]; then
	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"
	echo Error: You must be root to run this script!
	exit 1
fi

echo "Script to install sidux-binary-gfx"
echo ""

DATE=$(date +%D\ %T)
ME=$(basename $0)

trap nuke_me exit

sources_backup
dpkg -l | grep sidux-binary-gfx > /dev/null || install_me
[ -x /usr/sbin/install-binary-gfx ] || install_me

if [ -x /usr/sbin/install-binary-gfx ]; then
	if [ -n "$1" ]; then
		if [ "$1" = "--autorun" ]; then
			echo ""
			/usr/sbin/install-binary-gfx -a
		fi
	else
		echo ""
		echo "You can run \"install-binary-gfx -a\" now to build/install the Driver"
	fi
else
	echo ""
	echo "Failed to install sidux-binary-gfx. Please try again or install it manually."
fi

#END
