#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	if [ -x /usr/bin/su-me ]; then
		echo "Please enter root password:"
		DISPLAY="" exec su-me "$0" "$@"
	fi

	echo Error: You must be root to run this script!
	exit 1
fi

unset RESUME SWAPUUID

if [ -s /etc/initramfs-tools/conf.d/resume ]; then
	. /etc/initramfs-tools/conf.d/resume
fi

if [ -n "${RESUME}" ]; then
	echo -n "Validating resume partition..."

	case "${RESUME}" in
		UUID=*|LABEL=*)
			if findfs "${RESUME}"; then
				echo "Valid resume device: ${RESUME}"
				exit 0
			else
				echo "invalid."
			fi
			;;
		/dev/disk/by-*)
			RESUMELINK=$(readlink -f ${RESUME})
			if [ -b "${RESUMELINK}" ]; then
				echo "${RESUMELINK}"
				echo "Valid resume device: ${RESUME}"
				exit 0
			else
				echo "invalid."
			fi
			;;
		/dev/*)
			echo "invalid."
			if [ -b "${RESUME}" ]; then
				SWAPUUID=$(blkid -t TYPE=swap -o value -s UUID ${RESUME})
			fi
			;;
	esac
fi

if [ -z "${SWAPUUID}" ]; then
	SWAPUUID=$(blkid -l -t TYPE=swap -o value -s UUID)
fi

if echo "${SWAPUUID}" | egrep -q '^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$'; then
	echo "Using UUID=${SWAPUUID} for resume."
	if [ -d /etc/initramfs-tools/conf.d/ ]; then
		# (over)write configuration
		echo "Writing new configuration to /etc/initramfs-tools/conf.d/resume..."
		echo "RESUME=UUID=${SWAPUUID}" > /etc/initramfs-tools/conf.d/resume
	fi

	if grep -q -s '^resume device\ =' /etc/uswsusp.conf; then
		echo "Writing new configuration to /etc/uswsusp.conf..."
		sed -i 's|^\(resume\ device\ =\).*|\1 '"UUID=${SWAPUUID}"'|' /etc/uswsusp.conf
	fi
else
	echo "No swap partition UUID could be detected by blkid(8)."
	echo "Not configuring resume partition."
	exit 3
fi

if [ -x /usr/sbin/update-initramfs ]; then
	# rebuild the initramfs
	echo "Updating initial ramdisk for new resume configuration..."
	
	update-initramfs -u -k "$(uname -r)"
fi

if [ -w /boot/grub/menu.lst ] && egrep -q '# (defopt|kopt).*resume=[^[:space:]]+' /boot/grub/menu.lst; then
	# update grub menu.lst
	echo "Updating grub configuration /boot/grub/menu.lst..."

	# remove all resume= lines from grub menu.lst
	sed -i '/^# \(defopt\|kopt\)/s/[[:space:]]*resume=[^[:space:]]\+//' /boot/grub/menu.lst

	update-grub
fi

echo
echo "A new resume configuration has been written to:"
echo "  /etc/initramfs-tools/conf.d/resume"
echo
echo "If you do not trust me to make the correct choice, then please"
echo "check the file and change according to your needs."
echo
