#!/bin/sh
###############################################################
#
# Author: Andreas Weber <andreas@it-weber.com>
# Date: 16.01.2007
# Purpose: Script to install the sidux-binary-gfx Package
#
# Changelog:
# * 16.01.2007 Andreas Weber: Initial Release
#
#
# Todo:
#
#
###############################################################

sources_backup() {
	cp /etc/apt/sources.list /etc/apt/sources.backup
	cat > "/etc/apt/sources.list" \
	<<EOF
deb http://ftp.debian.org/debian/ sid main contrib non-free
deb http://sidux.net/debian/ sid main fix.main contrib non-free
EOF
	apt-get update || nuke_me
}

sources_restore() {
	cp /etc/apt/sources.backup /etc/apt/sources.list
}

clean_up() {
	apt-get update || nuke_me
}

install_me() {
	apt-get install sidux-binary-gfx
	sources_restore
	/usr/sbin/install-binary-gfx || nuke_me
	exit 0
}

nuke_me() {
	[ -f /etc/apt/sources.backup ] && cp /etc/apt/sources.backup /etc/apt/sources.list
	rm -f /etc/apt/sources.backup
	exit 1
}

# We have to be root. Oherwise we exit with exitcode 1
if [ ! $UID = "0" ]; then
	echo "You must be root to run this Script!"
	exit 1
fi

echo "Running $ME"
echo "Script to install sidux-binary-gfx"
echo ""

DATE=$(date +%D\ %T)
ME=$(basename $0)

trap nuke_me exit

sources_backup
dpkg -l | grep sidux-binary-gfx || install_me

#END