#!/bin/sh

echo|dh_make -s -c gpl

perl -pi -e 's/.*[hH][tT][mM][lL].*\n//' debian/$(basename $(pwd)|cut -d- -f1).doc-base.EX
perl -pi -e 's/(CFLAGS=)(\$\(CFLAGS\))/\1"\2"/' debian/rules
perl -pi -e 's/.\/configure (.*)/.\/configure \1 QTDIR=\/usr\/share\/qt3/' debian/rules

fakeroot debian/rules binary

