#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"

	echo Error: You must be root to run this script!
	exit 1
fi

RC="$(COLUMNS=200 dpkg -l|grep ^rc|awk '{print $2}')"

[ "$RC" ] && dpkg --purge $RC

