#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	[ -x /usr/bin/su-me ] && DISPLAY="" exec su-me "$0" "$@"

	echo Error: You must be root to run this script!
	exit 1
fi

if ! test -e /etc/network/interfaces.1st; then
	cp /etc/network/interfaces /etc/network/interfaces.1st
fi

perl -pi -e 's/^[\s]*gateway.*[\n]//g' /etc/network/interfaces

/etc/init.d/networking restart

