#!/usr/bin/perl
use strict;
@ARGV or die "Usage: $0 passphrase\n"; 
print generate_key( @ARGV ), "\n";

sub generate_key {
   require Digest::MD5;
   return substr Digest::MD5::md5_hex( substr( shift() x 64,  0, 64 ) ), 0, 26;
}